// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdOTp8tdTJQ36TAwH4RHoUE__A4QvmsoY',
    appId: '1:611363166289:web:3087866abe56327b634070',
    messagingSenderId: '611363166289',
    projectId: 'gurupi-semetes',
    authDomain: 'gurupi-semetes.firebaseapp.com',
    storageBucket: 'gurupi-semetes.firebasestorage.app',
    measurementId: 'G-PB9QX35N8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV9ikMnWBgSqDuo5JZh1mY3pD44KBRBdk',
    appId: '1:611363166289:android:b9120c564079b21b634070',
    messagingSenderId: '611363166289',
    projectId: 'gurupi-semetes',
    storageBucket: 'gurupi-semetes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6yZJb8jro5X_s22ii5pFgpzlD-F25Hw',
    appId: '1:611363166289:ios:b11d24f7982caaf0634070',
    messagingSenderId: '611363166289',
    projectId: 'gurupi-semetes',
    storageBucket: 'gurupi-semetes.firebasestorage.app',
    iosBundleId: 'com.example.sementesGurupi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6yZJb8jro5X_s22ii5pFgpzlD-F25Hw',
    appId: '1:611363166289:ios:b11d24f7982caaf0634070',
    messagingSenderId: '611363166289',
    projectId: 'gurupi-semetes',
    storageBucket: 'gurupi-semetes.firebasestorage.app',
    iosBundleId: 'com.example.sementesGurupi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdOTp8tdTJQ36TAwH4RHoUE__A4QvmsoY',
    appId: '1:611363166289:web:94a0a3f8291118da634070',
    messagingSenderId: '611363166289',
    projectId: 'gurupi-semetes',
    authDomain: 'gurupi-semetes.firebaseapp.com',
    storageBucket: 'gurupi-semetes.firebasestorage.app',
    measurementId: 'G-K8QNBQF0X5',
  );
}
